title:            Aryeh Kobrinsky
description:      New York bassist, composer and educator
kicker:           Bassist // Composer // Educator
disqus_shortname: 
reading_time:     false
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
paginate_path: "/posts/page:num/"
url: http://127.0.0.1:4000
collections:
 posts:
  output: true
 concerts:
  output: true
  permalink: /:year/:month/:day/:title/
 audios:
  output: false


defaults:
  - scope:
      path: ""
      type: concerts
    values:
      layout: concert
      breadcrumb: concerts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      breadcrumb: posts   
# Owner/author information
owner:
  name:           Aryeh Kobrinsky
  avatar:         avatar.jpg
  bio:            "Bassist, composer, educator living in New York"
  email:          aryeh.kobrinsky@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: aryehkobrinsky     
  facebook: shmaryeh    
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
