# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aryeh Kobrinsky
email: aryeh.kobrinsky@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  bassist / educator / composer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aryehkobrinsky.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shmaryeh
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate_path: "/posts/page:num/"
paginate: 5

# Build settings
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

owner:
  name:           Aryeh Kobrinsky
  avatar:         avatar.jpg
  bio:            "Bassist, composer, educator living in New York"
  email:          aryeh.kobrinsky@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: aryehkobrinsky     
  facebook: shmaryeh    
  github:         
  stackexchange:  
  linkedin:       
  instagram: akobrinsky
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus: 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
 posts:
  output: true
  future: true
  permalink: /:collection/:year/:month/:day/:title/
 concerts:
  output: true
  future: true
  published: true
  permalink: /:collection/:year/:month/:day/:title/
 audios:
  output: false

defaults:
  - scope:
      path: ""
      type: concerts
    values:
      layout: concert
      breadcrumb: concerts
      image:
       background:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      breadcrumb: posts 
